const SESSION_DAYS = 7;
const json = (data,status=200,extra={}) => new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}});
const cookieOptions = maxAge => `Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
function b64u(bytes){let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function b64uDecode(str){const pad='='.repeat((4-(str.length%4))%4);const raw=atob(str.replace(/-/g,'+').replace(/_/g,'/')+pad);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function sha256Base64(v){return b64u(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))}
async function randomToken(){return b64u(crypto.getRandomValues(new Uint8Array(32)))}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return `${b64u(salt)}.${b64u(bits)}`}
async function verifyPassword(password,encoded){try{const [salt]=encoded.split('.');return (await hashPassword(password,b64uDecode(salt)))===encoded}catch{return false}}
function parseCookie(h=''){const o={};for(const item of h.split(';')){const [k,...r]=item.trim().split('=');if(k)o[k]=r.join('=')}return o}
function sameOrigin(req){const o=req.headers.get('Origin');return !o||o===new URL(req.url).origin}
function cleanUser(r){if(!r)return null;const {password_hash,...u}=r;return u}
async function currentUser(req,env){const c=parseCookie(req.headers.get('Cookie')||'');if(!c.iurs_session)return null;const hash=await sha256Base64(c.iurs_session);const row=await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.status='active' LIMIT 1`).bind(hash).first();if(row)await env.DB.prepare(`UPDATE sessions SET last_seen_at=datetime('now') WHERE token_hash=?`).bind(hash).run();return cleanUser(row)}
const allowed = (u,roles=['admin','executive']) => !!u && roles.includes(u.role);
let schemaReady;
async function ensureSchema(env){
  if(schemaReady) return schemaReady;
  schemaReady=(async()=>{
    const stmts=[
      `CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,iurs_id TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('member','executive','admin')),name TEXT NOT NULL,email TEXT,department TEXT,year_level TEXT,position TEXT,phone TEXT,photo_url TEXT,status TEXT NOT NULL DEFAULT 'active',must_change_password INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS notices (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,level TEXT NOT NULL DEFAULT 'normal',published INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,image_url TEXT,link_url TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,event_date TEXT,event_time TEXT,venue TEXT,description TEXT,status TEXT NOT NULL DEFAULT 'upcoming',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,image_url TEXT,link_url TEXT,registration_url TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS publications (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,authors TEXT NOT NULL,category TEXT NOT NULL,journal TEXT,publication_year INTEGER,doi TEXT,url TEXT,abstract TEXT,published_status TEXT NOT NULL DEFAULT 'published',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,featured INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS site_stats (key TEXT PRIMARY KEY,value TEXT NOT NULL,label TEXT NOT NULL)`,
      `CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash)`,
      `CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role,status)`,
      `CREATE INDEX IF NOT EXISTS idx_publications_category_year ON publications(category,publication_year DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_events_status_date ON events(status,event_date)`,
      `CREATE INDEX IF NOT EXISTS idx_notices_published_created ON notices(published,created_at DESC)`,
      `INSERT OR IGNORE INTO site_stats(key,value,label) VALUES ('members','459+','Community Members'),('research_outputs','7','Research Outputs'),('workshops','6+','Workshops & Training'),('peer_reviewed','4','Peer-reviewed Articles'),('working_papers','10+','Working Papers'),('under_review','3+','Manuscripts Under Review')`
      `INSERT INTO events(title,event_date,event_time,venue,description,status,image_url) SELECT 'Orientation to Research Methodology','2026-05-03','9:30 AM','IIER Building, Room 101','Keynote by Professor Mohammed Asaduzzaman, PhD. Chair: Taqy Wasif. Host: Ashfia Kaniz Fatema.','past','assets/orientation-research-methodology-2026.jpg' WHERE NOT EXISTS (SELECT 1 FROM events)`,
      `INSERT INTO events(title,event_date,event_time,venue,description,status,image_url) SELECT 'The Unveiling: Research Insights & Leadership Transition','2025-08-12','9:00 AM – 4:00 PM','Gagan Harkara Gallery, Rabindra-Nazrul Arts Building','Panel seminar with faculty from Bangla, Arabic, Pharmacy, Chemical Engineering, and Social Welfare departments.','past','assets/event-unveiling-seminar-2025.jpg' WHERE (SELECT COUNT(*) FROM events)=1`,
      `INSERT INTO events(title,event_date,event_time,venue,description,status,image_url) SELECT 'Study in Europe: Opportunities, Admissions & Scholarships','2026-02-04','10:00 PM','Online','Speaker: Mohammad Nazmus Sakib, PhD Candidate, Daugavpils University, Latvia.','past','assets/webinar-study-europe-2026.jpg' WHERE (SELECT COUNT(*) FROM events)=2`,
      `INSERT INTO events(title,event_date,event_time,venue,description,status,image_url) SELECT 'Smart Office Tools for University Students','2026-02-25','Classes start 25 Feb','Online','Trainer: S. M. Shahriar Shadhin. Covers Word, PowerPoint, Excel and productivity skills.','past','assets/smart-office-tools-2026.jpg' WHERE (SELECT COUNT(*) FROM events)=3`,
      `INSERT INTO events(title,event_date,event_time,venue,description,status,image_url) SELECT 'Member Recruitment 4.1','2026-01-01','Registration ongoing','Islamic University, Kushtia','Open for students who want to explore research, improve writing and presentation skills, and join research workshops with mentorship support.','upcoming','assets/member-recruitment-4-1.jpg' WHERE (SELECT COUNT(*) FROM events)=4`
    ];
    for(const q of stmts) await env.DB.prepare(q).run();
    const columns={notices:[['image_url','TEXT'],['link_url','TEXT'],['updated_at','TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP']],events:[['image_url','TEXT'],['link_url','TEXT'],['registration_url','TEXT'],['updated_at','TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP']],publications:[['featured','INTEGER NOT NULL DEFAULT 0'],['updated_at','TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP']]};
    for(const [table,cols] of Object.entries(columns)){
      const info=await env.DB.prepare(`PRAGMA table_info(${table})`).all();const have=new Set((info.results||[]).map(x=>x.name));
      for(const [name,type] of cols) if(!have.has(name)) await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${name} ${type}`).run();
    }
  })().catch(e=>{schemaReady=null;throw e});
  return schemaReady;
}
const body = req => req.json().catch(()=>({}));
function cleanUrl(v){const s=String(v||'').trim();return s||null}
function cleanText(v,max=10000){return String(v??'').trim().slice(0,max)}
function isoDate(v){const s=cleanText(v,20);return s||null}

async function login(req,env){if(!sameOrigin(req))return json({error:'Invalid origin'},403);const b=await body(req);const id=cleanText(b.iursId,80).toUpperCase(),pw=String(b.password||'');if(!id||!pw)return json({error:'IURS ID and password are required.'},400);const row=await env.DB.prepare('SELECT * FROM users WHERE upper(iurs_id)=? LIMIT 1').bind(id).first();if(!row||row.status!=='active'||!(await verifyPassword(pw,row.password_hash)))return json({error:'Invalid IURS ID or password.'},401);const token=await randomToken(),hash=await sha256Base64(token),expires=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,?)').bind(row.id,hash,expires).run();const target=row.role==='member'?'/dashboard.html':'/admin.html';return json({ok:true,user:cleanUser(row),redirect:target},200,{'Set-Cookie':`iurs_session=${token}; ${cookieOptions(SESSION_DAYS*86400)}`})}
async function logout(req,env){const c=parseCookie(req.headers.get('Cookie')||'');if(c.iurs_session)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256Base64(c.iurs_session)).run();return json({ok:true},200,{'Set-Cookie':`iurs_session=; ${cookieOptions(0)}`})}
async function setup(req,env){if(!sameOrigin(req))return json({error:'Invalid origin'},403);const token=req.headers.get('X-IURS-Setup-Token')||'';if(env.SETUP_TOKEN && token!==env.SETUP_TOKEN)return json({error:'Invalid setup token.'},403);const c=await env.DB.prepare('SELECT COUNT(*) c FROM users').first();if(Number(c?.c||0)>0)return json({error:'Initial setup is already complete.'},409);const b=await body(req);const id=cleanText(b.iursId,80).toUpperCase(),name=cleanText(b.name,160),email=cleanText(b.email,200),position=cleanText(b.position||'General Secretary',120),pw=String(b.password||'');if(!id||!name||pw.length<10)return json({error:'Name, IURS ID and password (10+ characters) are required.'},400);const ph=await hashPassword(pw,crypto.getRandomValues(new Uint8Array(16)));await env.DB.prepare('INSERT INTO users(iurs_id,password_hash,role,name,email,position,must_change_password) VALUES(?,?,?,?,?,?,0)').bind(id,ph,'admin',name,email,position).run();return json({ok:true,message:'Admin created. You can now sign in.'})}

async function changePassword(req,env,user){if(!user)return json({error:'Authentication required.'},401);const b=await body(req),old=String(b.currentPassword||''),next=String(b.newPassword||'');const row=await env.DB.prepare('SELECT password_hash FROM users WHERE id=?').bind(user.id).first();if(!row||!(await verifyPassword(old,row.password_hash)))return json({error:'Current password is incorrect.'},400);if(next.length<10)return json({error:'New password must be at least 10 characters.'},400);const ph=await hashPassword(next,crypto.getRandomValues(new Uint8Array(16)));await env.DB.prepare("UPDATE users SET password_hash=?,must_change_password=0,updated_at=datetime('now') WHERE id=?").bind(ph,user.id).run();return json({ok:true})}

async function adminApi(req,env,user,path){if(!allowed(user))return json({error:'Executive access required.'},403);const m=req.method;
 if(path==='/api/admin/summary'&&m==='GET'){const [members,execs,papers,events,notices]=await Promise.all([env.DB.prepare("SELECT COUNT(*) c FROM users WHERE role='member' AND status='active'").first(),env.DB.prepare("SELECT COUNT(*) c FROM users WHERE role IN ('executive','admin') AND status='active'").first(),env.DB.prepare('SELECT COUNT(*) c FROM publications').first(),env.DB.prepare('SELECT COUNT(*) c FROM events').first(),env.DB.prepare('SELECT COUNT(*) c FROM notices WHERE published=1').first()]);return json({members:+members.c,executives:+execs.c,publications:+papers.c,events:+events.c,notices:+notices.c})}
 if(path==='/api/admin/members'&&m==='GET'){const r=await env.DB.prepare('SELECT id,iurs_id,name,email,department,year_level,position,phone,status,role,must_change_password,created_at FROM users ORDER BY id DESC').all();return json(r.results||[])}
 if(path==='/api/admin/members'&&m==='POST'){const b=await body(req),id=cleanText(b.iursId,80).toUpperCase(),name=cleanText(b.name,160),pw=String(b.password||'');if(!id||!name||pw.length<10)return json({error:'IURS ID, name and a 10+ character password are required.'},400);let role=b.role==='executive'?'executive':'member';if(role==='executive'&&user.role!=='admin')return json({error:'Only administrators can create executives.'},403);try{const ph=await hashPassword(pw,crypto.getRandomValues(new Uint8Array(16)));await env.DB.prepare('INSERT INTO users(iurs_id,password_hash,role,name,email,department,year_level,position,phone,must_change_password) VALUES(?,?,?,?,?,?,?,?,?,1)').bind(id,ph,role,name,cleanText(b.email,200)||null,cleanText(b.department,160)||null,cleanText(b.yearLevel,40)||null,cleanText(b.position,120)||null,cleanText(b.phone,60)||null).run()}catch(e){return json({error:'Could not create account. The IURS ID may already exist.'},400)}return json({ok:true})}
 if(path.startsWith('/api/admin/members/')&&m==='PUT'){const id=Number(path.split('/').pop());const target=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(id).first();if(!target)return json({error:'User not found.'},404);const b=await body(req);if(target.role==='admin'&&user.role!=='admin')return json({error:'Administrator account requires administrator access.'},403);if(b.role && b.role!==target.role && user.role!=='admin')return json({error:'Only administrators can change account roles.'},403);const role=b.role?((b.role==='admin'&&user.role==='admin')?'admin':(b.role==='executive'?'executive':'member')):target.role;if(role==='admin'&&user.role!=='admin')return json({error:'Only administrators can assign admin role.'},403);await env.DB.prepare("UPDATE users SET name=?,email=?,department=?,year_level=?,position=?,phone=?,role=?,status=?,updated_at=datetime('now') WHERE id=?").bind(cleanText(b.name,160)||target.name,cleanText(b.email,200)||null,cleanText(b.department,160)||null,cleanText(b.yearLevel,40)||null,cleanText(b.position,120)||null,cleanText(b.phone,60)||null,role,['active','inactive','suspended'].includes(b.status)?b.status:target.status,id).run();return json({ok:true})}
 if(path.startsWith('/api/admin/members/')&&m==='DELETE'){if(user.role!=='admin')return json({error:'Only administrators can deactivate accounts.'},403);const id=Number(path.split('/').pop());await env.DB.prepare("UPDATE users SET status='inactive',updated_at=datetime('now') WHERE id=? AND role!='admin'").bind(id).run();return json({ok:true})}
 if(path.match(/^\/api\/admin\/members\/\d+\/reset-password$/)&&m==='POST'){const id=Number(path.split('/')[4]);const b=await body(req),pw=String(b.password||'');if(pw.length<10)return json({error:'Password must be at least 10 characters.'},400);const ph=await hashPassword(pw,crypto.getRandomValues(new Uint8Array(16)));await env.DB.prepare("UPDATE users SET password_hash=?,must_change_password=1,updated_at=datetime('now') WHERE id=?").bind(ph,id).run();return json({ok:true})}
 if(path==='/api/admin/stats'&&m==='PUT'){const b=await body(req);for(const key of ['members','research_outputs','workshops','peer_reviewed','working_papers','under_review'])if(b[key]!=null)await env.DB.prepare('INSERT INTO site_stats(key,value,label) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,cleanText(b[key],50),key).run();return json({ok:true})}
 if(path==='/api/admin/publications'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM publications ORDER BY publication_year DESC,id DESC').all();return json(r.results||[])}
 if(path==='/api/admin/publications'&&m==='POST'){const b=await body(req);if(!cleanText(b.title,500)||!cleanText(b.authors,1000)||!cleanText(b.category,50))return json({error:'Title, authors and category are required.'},400);await env.DB.prepare('INSERT INTO publications(title,authors,category,journal,publication_year,doi,url,abstract,published_status,featured) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(cleanText(b.title,500),cleanText(b.authors,1000),cleanText(b.category,50),cleanText(b.journal,300)||null,Number(b.year)||null,cleanText(b.doi,200)||null,cleanUrl(b.url),cleanText(b.abstract,8000)||null,cleanText(b.publishedStatus||'published',40),b.featured?1:0).run();return json({ok:true})}
 if(path.startsWith('/api/admin/publications/')&&m==='PUT'){const id=Number(path.split('/').pop()),b=await body(req);await env.DB.prepare('UPDATE publications SET title=?,authors=?,category=?,journal=?,publication_year=?,doi=?,url=?,abstract=?,published_status=?,featured=?,updated_at=datetime(\'now\') WHERE id=?').bind(cleanText(b.title,500),cleanText(b.authors,1000),cleanText(b.category,50),cleanText(b.journal,300)||null,Number(b.year)||null,cleanText(b.doi,200)||null,cleanUrl(b.url),cleanText(b.abstract,8000)||null,cleanText(b.publishedStatus||'published',40),b.featured?1:0,id).run();return json({ok:true})}
 if(path.startsWith('/api/admin/publications/')&&m==='DELETE'){const id=Number(path.split('/').pop());await env.DB.prepare('DELETE FROM publications WHERE id=?').bind(id).run();return json({ok:true})}
 if(path==='/api/admin/events'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM events ORDER BY CASE WHEN status=\'upcoming\' THEN 0 ELSE 1 END,event_date DESC,id DESC').all();return json(r.results||[])}
 if(path==='/api/admin/events'&&m==='POST'){const b=await body(req);if(!cleanText(b.title,400))return json({error:'Event title is required.'},400);await env.DB.prepare('INSERT INTO events(title,event_date,event_time,venue,description,status,image_url,link_url,registration_url) VALUES(?,?,?,?,?,?,?,?,?)').bind(cleanText(b.title,400),isoDate(b.date),cleanText(b.time,80)||null,cleanText(b.venue,300)||null,cleanText(b.description,5000)||null,['upcoming','past','cancelled'].includes(b.status)?b.status:'upcoming',cleanUrl(b.imageUrl),cleanUrl(b.linkUrl),cleanUrl(b.registrationUrl)).run();return json({ok:true})}
 if(path.startsWith('/api/admin/events/')&&m==='PUT'){const id=Number(path.split('/').pop()),b=await body(req);await env.DB.prepare('UPDATE events SET title=?,event_date=?,event_time=?,venue=?,description=?,status=?,image_url=?,link_url=?,registration_url=?,updated_at=datetime(\'now\') WHERE id=?').bind(cleanText(b.title,400),isoDate(b.date),cleanText(b.time,80)||null,cleanText(b.venue,300)||null,cleanText(b.description,5000)||null,['upcoming','past','cancelled'].includes(b.status)?b.status:'upcoming',cleanUrl(b.imageUrl),cleanUrl(b.linkUrl),cleanUrl(b.registrationUrl),id).run();return json({ok:true})}
 if(path.startsWith('/api/admin/events/')&&m==='DELETE'){await env.DB.prepare('DELETE FROM events WHERE id=?').bind(Number(path.split('/').pop())).run();return json({ok:true})}
 if(path==='/api/admin/notices'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM notices ORDER BY published DESC,created_at DESC,id DESC').all();return json(r.results||[])}
 if(path==='/api/admin/notices'&&m==='POST'){const b=await body(req);if(!cleanText(b.title,400)||!cleanText(b.body,5000))return json({error:'Notice title and body are required.'},400);await env.DB.prepare('INSERT INTO notices(title,body,level,published,image_url,link_url) VALUES(?,?,?,?,?,?)').bind(cleanText(b.title,400),cleanText(b.body,5000),['urgent','high','normal'].includes(b.level)?b.level:'normal',b.published===false?0:1,cleanUrl(b.imageUrl),cleanUrl(b.linkUrl)).run();return json({ok:true})}
 if(path.startsWith('/api/admin/notices/')&&m==='PUT'){const id=Number(path.split('/').pop()),b=await body(req);await env.DB.prepare('UPDATE notices SET title=?,body=?,level=?,published=?,image_url=?,link_url=?,updated_at=datetime(\'now\') WHERE id=?').bind(cleanText(b.title,400),cleanText(b.body,5000),['urgent','high','normal'].includes(b.level)?b.level:'normal',b.published===false?0:1,cleanUrl(b.imageUrl),cleanUrl(b.linkUrl),id).run();return json({ok:true})}
 if(path.startsWith('/api/admin/notices/')&&m==='DELETE'){await env.DB.prepare('DELETE FROM notices WHERE id=?').bind(Number(path.split('/').pop())).run();return json({ok:true})}
 return json({error:'Not found'},404)}

async function publicApi(req,env,path){
 if(path==='/api/public/stats')return json(Object.fromEntries(((await env.DB.prepare('SELECT key,value,label FROM site_stats').all()).results||[]).map(r=>[r.key,{value:r.value,label:r.label}])));
 if(path==='/api/public/publications'){const r=await env.DB.prepare("SELECT * FROM publications WHERE published_status='published' ORDER BY publication_year DESC,id DESC").all();return json(r.results||[])}
 if(path==='/api/public/events'){const r=await env.DB.prepare('SELECT * FROM events ORDER BY CASE WHEN status=\'upcoming\' THEN 0 ELSE 1 END,event_date DESC,id DESC').all();return json(r.results||[])}
 if(path==='/api/public/notices'){const r=await env.DB.prepare('SELECT * FROM notices WHERE published=1 ORDER BY created_at DESC,id DESC').all();return json(r.results||[])}
 return json({error:'Not found'},404)}

export default {async fetch(request,env,ctx){const url=new URL(request.url);try{await ensureSchema(env);if(url.pathname.startsWith('/api/')){const user=await currentUser(request,env);if(request.method==='POST'&&url.pathname==='/api/auth/login')return await login(request,env);if(request.method==='POST'&&url.pathname==='/api/auth/logout')return await logout(request,env);if(request.method==='POST'&&url.pathname==='/api/auth/change-password')return await changePassword(request,env,user);if(request.method==='POST'&&url.pathname==='/api/setup/initial-admin')return await setup(request,env);if(request.method==='GET'&&url.pathname==='/api/auth/me')return json({authenticated:!!user,user});if(url.pathname.startsWith('/api/admin/'))return await adminApi(request,env,user,url.pathname);if(url.pathname.startsWith('/api/public/'))return await publicApi(request,env,url.pathname);if(url.pathname==='/api/health')return json({ok:true,service:'IURS full-stack backend'});return json({error:'Not found'},404)}const asset=await env.ASSETS.fetch(request);const h=new Headers(asset.headers);h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','strict-origin-when-cross-origin');h.set('X-Frame-Options','SAMEORIGIN');return new Response(asset.body,{status:asset.status,statusText:asset.statusText,headers:h})}catch(e){console.error(e);return json({error:'Server error. Please try again.'},500)}}};
